name: escu-manual-workflow
on:
  workflow_dispatch:
    inputs:
      TA_BUILD:
        description: 'TA build number (e.g. s3://ta-production-artifacts/ta-apps/{ta-name}-$build_number$.spl)'
        required: true
      TESTS:
        description: 'Comma-Separated List of detections to run (e.g. detection1,detection2,detection3)'
        required: true

jobs:
  call-workflow:
    uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-escu-manual-workflow.yml@v2.1
    with:
      TA_BUILD: ${{ inputs.TA_BUILD }}
      TESTS: ${{ inputs.TESTS }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      OTHER_TA_REQUIRED_CONFIGS: ${{ secrets.OTHER_TA_REQUIRED_CONFIGS }}
